[package]
name = "scs-sdk-plugin-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "ABI export macros for safe Rust SCS Telemetry and Input plugins"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[lints]
workspace = true
